#!/bin/sh

set -e
set -u

# Docker Desktop started to crash when building the image
# podman at least told me installing Crystal with mise ran out of memory
#
# docker build . --tag ai:latest

# check date when it was built with
# podman image inspect ai:latest | jq '.[].Created'

EXTRA_ARGS=""

for arg in "$@"; do
  case "$arg" in
    --force)
      EXTRA_ARGS="--no-cache --pull"
      ;;
  esac
done

set -x
podman build $EXTRA_ARGS . --tag ai:latest
