#!/bin/sh

set -eux

apt-get update
apt-get install -y \
  build-essential\
  cmake \
  curl \
  gcc \
  git \
  postgresql \
  sudo \
  zsh

sh _mise.sh
echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
source ~/.bashrc

sh _rv.sh
echo 'eval "$(rv shell init bash)"' >> ~/.bashrc
echo 'eval "$(rv shell completions bash)"' >> ~/.bashrc
source ~/.bashrc

rv ruby install 3.4.7
source ~/.bashrc

gem install bundler

mise use --global \
  bun \
  crystal \
  go \
  node \
  python \
  rust

bundle --version
crystal version
go version
node --version
python --version
ruby --version --yjit
rustc --version

npm install -g @anthropic-ai/claude-code
npm install -g @github/copilot
npm install -g @google/gemini-cli
