#!/bin/sh

set -eu

function download() {
  local name=$1
  local url=$2

  curl --location --silent --output inside_deps/_${name}.sh ${url}
  echo "✓ ${name}"
}

download brew https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
download claude https://claude.ai/install.sh
download mise https://mise.run
download nvm https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh
download rv https://github.com/spinel-coop/rv/releases/download/v0.5.3/rv-installer.sh
